name: Python CI

on:
  push:
    branches:
      - main
      - task-1
      - task-2
      - task-3
      - task-4
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scripts / tests
      run: |
        # Run your test scripts or linting here
        # For example, you can run a test script or a linter:
        # pytest tests/
        # flake8 .
        python your_script.py
